# Generated by Django 6.0.5 on 2026-07-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='full_name',
            new_name='name',
        ),
    ]
